var videoData = {
  title: "视频标题",
  img: "./images/u0.jpg",
  type: "视频类型",
  userComment: [{
    userImg: "/images/QQ.png",
    userName: "评论用户1",
    comment: "视频很好看"
  }, {
      userImg: "/images/QQ.png",
      userName: "评论用户2",
      comment: "视频很好看"
    }, {
      userImg: "/images/QQ.png",
      userName: "评论用户3",
      comment: "视频很好看"
    }, {
      userImg: "/images/QQ.png",
      userName: "评论用户4",
      comment: "视频很好看"
    }],
  pages: [{
    title: "第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
};

var recommed = [{
  title: "推荐视频标题0",
  img: "./images/u0.jpg",
  type: "推荐视频类型",
  userComment: [],
  pages: [{
    title: "推荐第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "推荐第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "推荐第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
}, {
  title: "推荐视频标题1",
  img: "./images/u0.jpg",
  type: "推荐视频类型",
  userComment: [],
  pages: [{
    title: "推荐第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "推荐第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "推荐第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }, {
    title: "推荐第四集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
}, {
  title: "推荐视频标题2",
  img: "./images/u0.jpg",
  type: "推荐视频类型",
  userComment: [],
  pages: [{
    title: "推荐第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "推荐第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "推荐第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }, {
    title: "推荐第四集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }, {
    title: "推荐第五集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
}, {
  title: "推荐视频标题3",
  img: "./images/u0.jpg",
  type: "推荐视频类型",
  userComment: [],
  pages: [{
    title: "推荐第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "推荐第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "推荐第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
}, {
  title: "推荐视频标题4",
  img: "./images/u0.jpg",
  type: "推荐视频类型",
  userComment: [],
  pages: [{
    title: "推荐第一集标题",
    url: "./videos/1.mp4",
    time: "00:07",
  }, {
    title: "推荐第二集标题",
    url: "./videos/test2.mp4",
    time: "00:07",
  }, {
    title: "推荐第三集标题",
    url: "./videos/test3.mp4",
    time: "00:07",
  }]
}];
